----------------------------------------------------------------------
-- Name: RandomDrivePoints
-- Description: List of points in the world to use for the random drive tests
-- Owner: pkg
-- (c) 2005 Real Time Worlds
----------------------------------------------------------------------

-- This list of points is generated by moving the player to a position and
-- then noting down the co-ordinates from the Player debug page
avRandomDrivePoints = CreateReadOnly
{
	-- Small set of test points in fairly close proximity to the players start point
--	--[[
	MakeVec3(   942,     45,  -1598),
	MakeVec3(  1365,     22,  -1361),
	MakeVec3(   934,     43,  -1375),
	MakeVec3(  1077,     43,  -1635),
--	]]--
}