----------------------------------------------------------------------
-- Name: RandomWalkPoints
-- Description: List of points in the world to use for the random walk tests
-- Owner: pkg
-- (c) 2005 Real Time Worlds
----------------------------------------------------------------------

-- This list of points is generated by moving the player to a position and
-- then noting down the co-ordinates from the Player debug page
avRandomWalkPoints = CreateReadOnly
{
	-- Small set of test points, all in extremely close proximity to the players start point
	--[[
	MakeVec3(  1011.99,     42.95,  -1464.51),
	MakeVec3(  1013.81,     42.95,  -1477.42),
	MakeVec3(  1002.13,     42.95,  -1468.43),
	]]--

	-- Larger set of points, distributed fairly close to the player start point
--	--[[
	MakeVec3(  1090.43,     33.28,  -1366.67),
	MakeVec3(  1058.01,     38.12,  -1244.24),
	MakeVec3(   922.41,     42.53,  -1328.79),
	MakeVec3(   938.71,     49.02,  -1462.33),
	MakeVec3(   991.43,     46.22,  -1489.65),
--	]]--
}