----------------------------------------------------------------------
-- Name: Patrol Route Names
-- Description: A	single unified list of all the patrol routes used in the game
-- Owner: Nathan, Ed, Bill
-- (c) 2005 Real Time Worlds
----------------------------------------------------------------------

-- require "System\\ReadOnly"

ePatrolRouteNames = -- CreateReadOnly
{
	
--------- Nightclub - BillG	
	
	-- Bouncers  
	sNC_DrGrd1 		= "Default\\NightClub\\NC_DrGrd1_patrol",
	sNC_DrGrd2 		= "Default\\NightClub\\NC_DrGrd2_patrol",
	sNC_MainDrGrd1 		= "Default\\NightClub\\NC_MainDrGrd1_patrol",
	sNC_MainDrGrd2 		= "Default\\NightClub\\NC_MainDrGrd2_patrol",
	
	-- Left door def squad
	sNC_LftDrGrd01		= "Default\\NightClub\\NC_LftDrGrd01_patrol",
	sNC_LftDrGrd02 		= "Default\\NightClub\\NC_LftDrGrd2_patrol",
	sNC_LftDr2ManPat01	= "Default\\NightClub\\NC_LftDr2ManPat_patrol",
	sNC_LftDr2ManPat02	= "Default\\NightClub\\NC_LftDr2ManPat02_patrol",
		
	-- Right door def squad
	sNC_RgtDrGrd2 		= "Default\\NightClub\\NC_RgtDrGrd2_patrol",
	sNC_RgtDrGrd 		= "Default\\NightClub\\NC_RgtDrGrd_patrol",
	sNC_RgtDr2ManPat01	= "Default\\NightClub\\NC_RgtDr2ManPat_patrol",
	sNC_RgtDr2ManPat02	= "Default\\NightClub\\NC_RgtDr2ManPat02_patrol",
		
	-- Car park entrance def squad
	sNC_CrPrkGrd01 		= "Default\\NightClub\\NC_CrPrkGrde01_patrol",
	sNC_CrPrkGrd02 		= "Default\\NightClub\\NC_CrPrkGrd02_patrol",
	sNC_CrPrkGrd03 		= "Default\\NightClub\\NC_CrPrkGrd03_patrol",
	sNC_CrPrkGrd04 		= "Default\\NightClub\\NC_CrPrkGrd04_patrol",
	
	-- Middle balcony cloak room squads
	sNC_DefGuardInt1		= "Default\\NightClub\\NC_DefGuardInt1_patrol",
	sNC_DefGuardInt2		= "Default\\NightClub\\NC_DefGuardInt2_patrol",
	sNC_DefGuardInt3		= "Default\\NightClub\\NC_DefGuardInt3_patrol",
	sNC_DefGuardInt4		= "Default\\NightClub\\NC_DefGuardInt4_patrol",
	sNC_DefGuardInt5		= "Default\\NightClub\\NC_DefGuardInt5_patrol",
	sNC_DefGuardInt6		= "Default\\NightClub\\NC_DefGuardInt6_patrol",
	sNC_DefGuardInt7		= "Default\\NightClub\\NC_DefGuardInt7_patrol",
	sNC_DefGuardInt8		= "Default\\NightClub\\NC_DefGuardInt8_patrol",

	-- Forward roof guards		
	sNC_DefGuardRoof1		= "Default\\NightClub\\NC_DefGuardRoof1_patrol",
	sNC_DefGuardRoof2		= "Default\\NightClub\\NC_DefGuardRoof2_patrol",
	sNC_DefGuardRoof3		= "Default\\NightClub\\NC_DefGuardRoof3_patrol",
	sNC_DefGuardRoof4		= "Default\\NightClub\\NC_DefGuardRoof4_patrol",
	sNC_DefGuardRoof5		= "Default\\NightClub\\NC_DefGuardRoof5_patrol",
	sNC_DefGuardRoof6		= "Default\\NightClub\\NC_DefGuardRoof6_patrol",
	sNC_DefGuardRoof7		= "Default\\NightClub\\NC_DefGuardRoof7_patrol",
	sNC_DefGuardRoof8		= "Default\\NightClub\\NC_DefGuardRoof8_patrol",
	
	-- VIP lounge support
	sNC_DefGuardVIPLow1		= "Default\\NightClub\\NC_DefGuardVIPLow1_patrol",
	sNC_DefGuardVIPLow2		= "Default\\NightClub\\NC_DefGuardVIPLow2_patrol",
	sNC_DefGuardVIPLow3		= "Default\\NightClub\\NC_DefGuardVIPLow3_patrol",
	sNC_DefGuardVIPLow4		= "Default\\NightClub\\NC_DefGuardVIPLow4_patrol",
	
	-- Lone patrolling guard
	sNC_CrPrk3ManPat		= "Default\\NightClub\\NC_CrPrk3ManPat_patrol",
	
	-- Unused 
	sNC_SeedPoint		= "Default\\NightClub\\NC_SeedPoint_patrol",


--------- Villa - BillG	- TO BE UPDATED
	sVi_Bridge_patrol 	= "Default\\Villa\\Vi_Bridge_patrol",
	sVi_MainLandGateCent 	= "Default\\Villa\\Vi_MainLandGateCent_patrol",
	sVi_MainLandGateCent02 	= "Default\\Villa\\Vi_MainLandGateCent02_patrol",
	sVi_MainLandGateLft 	= "Default\\Villa\\Vi_MainLandGateLft_patrol",
	sVi_MainLandGateLft02 	= "Default\\Villa\\Vi_MainLandGateLft02_patrol",
	sVi_MainLndGateRgt	= "Default\\Villa\\Vi_MainLandGateRgt02_patrol",
	sVi_MainLandGateRgt02	= "Default\\Villa\\Vi_MainLndGateRgt_patrol",
	
	sVi_MainLndSniper	= "Default\\Villa\\Vi_MainLndSniper_patrol",
		
	sVi_CourtYrdSniper01	= "Default\\Villa\\Vi_CourtYrdSniper01_patrol",
	sVi_CourtYrdSniper02	= "Default\\Villa\\Vi_CourtYrdSniper02_patrol",
			
	sVi_DefGuardA01		= "Default\\Villa\\Vi_DefGuardA01_patrol",
	sVi_DefGuardA02		= "Default\\Villa\\Vi_DefGuardA02_patrol",
	sVi_DefGuardA03		= "Default\\Villa\\Vi_DefGuardA03_patrol",
	sVi_DefGuardA04		= "Default\\Villa\\Vi_DefGuardA04_patrol",
	
	sVi_DefGuardB01 	= "Default\\Villa\\Vi_DefGuardB01_patrol",
	sVi_DefGuardB02		= "Default\\Villa\\Vi_DefGuardB02_patrol",
	sVi_DefGuardB03		= "Default\\Villa\\Vi_DefGuardB03_patrol",
	sVi_DefGuardB04		= "Default\\Villa\\Vi_DefGuardB04_patrol",
		
	sVi_DefGuardC01		= "Default\\Villa\\Vi_DefGuardC01_patrol",
	sVi_DefGuardC02		= "Default\\Villa\\Vi_DefGuardC02_patrol",
	sVi_DefGuardC03		= "Default\\Villa\\Vi_DefGuardC03_patrol",
	sVi_DefGuardC04		= "Default\\Villa\\Vi_DefGuardC04_patrol",
	
	sVi_DefGuardD01		= "Default\\Villa\\Vi_DefGuardD01_patrol",
	sVi_DefGuardD02		= "Default\\Villa\\Vi_DefGuardD02_patrol",
	sVi_DefGuardD03		= "Default\\Villa\\Vi_DefGuardD03_patrol",	
	sVi_DefGuardD04		= "Default\\Villa\\Vi_DefGuardD04_patrol",
	
	sVi_DefGuardE01		= "Default\\Villa\\Vi_DefGuardE01_patrol",
	sVi_DefGuardE02		= "Default\\Villa\\Vi_DefGuardE02_patrol",
	sVi_DefGuardE03		= "Default\\Villa\\Vi_DefGuardE03_patrol",
	sVi_DefGuardE04		= "Default\\Villa\\Vi_DefGuardE04_patrol",
	
	sVi_DefGuardF01		= "Default\\Villa\\Vi_DefGuardF01_patrol",
	sVi_DefGuardF02		= "Default\\Villa\\Vi_DefGuardF02_patrol",
	sVi_DefGuardF03		= "Default\\Villa\\Vi_DefGuardF03_patrol",
	sVi_DefGuardF04		= "Default\\Villa\\Vi_DefGuardF04_patrol",
	
	sVi_DefGuardG01		= "Default\\Villa\\Vi_DefGuardG01_patrol",
	sVi_DefGuardG02		= "Default\\Villa\\Vi_DefGuardG02_patrol",
	sVi_DefGuardG03		= "Default\\Villa\\Vi_DefGuardG03_patrol",
	sVi_DefGuardG04		= "Default\\Villa\\Vi_DefGuardG04_patrol",
	
	sVi_DefGuardH01		= "Default\\Villa\\Vi_DefGuardH01_patrol",
	sVi_DefGuardH02		= "Default\\Villa\\Vi_DefGuardH02_patrol",
	sVi_DefGuardH03		= "Default\\Villa\\Vi_DefGuardH03_patrol",
	sVi_DefGuardH04		= "Default\\Villa\\Vi_DefGuardH04_patrol",
	
	sVi_DefGuardI01		= "Default\\Villa\\Vi_DefGuardI01_patrol",
	sVi_DefGuardI02		= "Default\\Villa\\Vi_DefGuardI02_patrol",
	sVi_DefGuardI03		= "Default\\Villa\\Vi_DefGuardI03_patrol",
	sVi_DefGuardI04		= "Default\\Villa\\Vi_DefGuardI04_patrol",
	sVi_DefGuardI05		= "Default\\Villa\\Vi_DefGuardI05_patrol",
	sVi_DefGuardI06		= "Default\\Villa\\Vi_DefGuardI06_patrol",
	sVi_DefGuardI07		= "Default\\Villa\\Vi_DefGuardI07_patrol",
	
	sVi_DefGuardJ01		= "Default\\Villa\\Vi_DefGuardJ01_patrol",
	sVi_DefGuardJ02		= "Default\\Villa\\Vi_DefGuardJ02_patrol",
	sVi_DefGuardJ03		= "Default\\Villa\\Vi_DefGuardJ03_patrol",
	sVi_DefGuardJ04		= "Default\\Villa\\Vi_DefGuardJ04_patrol",
	
	sVi_DefGuardK01		= "Default\\Villa\\Vi_DefGuardK01_patrol",
	sVi_DefGuardK02		= "Default\\Villa\\Vi_DefGuardK02_patrol",
	sVi_DefGuardK03		= "Default\\Villa\\Vi_DefGuardK03_patrol",
	sVi_DefGuardK04		= "Default\\Villa\\Vi_DefGuardK04_patrol",
	
	sVi_ShootBarrelGuard	= "Default\\Villa\\Vi_ShootBarrelGuard_patrol",
	
	sVi_BossBedroomSeedPoint01	= "Default\\Villa\\Vi_BossBedroomSeedPoint01_patrol",
	sVi_BossBedroomSeedPoint02	= "Default\\Villa\\Vi_BossBedroomSeedPoint02_patrol",
		
	
--------- Hillside Housing - BillG - TO BE UPDATED
	sHill_MainEntC 		= "Default\\HillsideHousing\\Hill_MainEntC_patrol",
	sHill_MainEntB 		= "Default\\HillsideHousing\\Hill_MainEntB_patrol",
	sHill_MainEntA 		= "Default\\HillsideHousing\\Hill_MainEntA_patrol",
		
	sHill_LowLevC 		= "Default\\HillsideHousing\\Hill_LowLevC_patrol",
	sHill_LowLevB 		= "Default\\HillsideHousing\\Hill_LowLevB_patrol",
	sHill_LowLevA 		= "Default\\HillsideHousing\\Hill_LowLevA_patrol",
		
	sHill_GngEntC 		= "Default\\HillsideHousing\\Hill_GngEntC_patrol",
	sHill_GngEntB 		= "Default\\HillsideHousing\\Hill_GngEntB_patrol",
	sHill_GngEntA 		= "Default\\HillsideHousing\\Hill_GngEntA_patrol",
		
	sHill_BalconyB		= "Default\\HillsideHousing\\Hill_BalconyB_patrol",
	sHill_BalconyA 		= "Default\\HillsideHousing\\Hill_BalconyA_patrol",
	sHill_RearBalc01	= "Default\\HillsideHousing\\Hill_RearBalc01_patrol",
		
	sHill_Sniper01 		= "Default\\HillsideHousing\\Hill_Sniper01_patrol",
	sHill_Sniper02 		= "Default\\HillsideHousing\\Hill_Sniper02_patrol",
		
	sHill_OutPat02 		= "Default\\HillsideHousing\\Hill_OutPat02_patrol",
	sHill_OutPat01 		= "Default\\HillsideHousing\\Hill_OutPat01_patrol",
		
	sHill_Gate02 		= "Default\\HillsideHousing\\Hill_Gate02_patrol",
	sHill_Gate01 		= "Default\\HillsideHousing\\Hill_Gate01_patrol",
		
	sHill_MainEntRoofSnip 	= "Default\\HillsideHousing\\Hill_MainEntRoofSnip_patrol",
	
	--not actually used for patrols just for seed point creation
	sHill_MainEntRoofSeedPoint = "Default\\HillsideHousing\\Hill_MainEntRoofSeedPoint_patrol",
	
	--Scripted Guards
	sHill_DefGuardA01 = "Default\\HillsideHousing\\Hill_DefGuardA01_patrol",
	sHill_DefGuardA02 = "Default\\HillsideHousing\\Hill_DefGuardA02_patrol",
	sHill_DefGuardA03 = "Default\\HillsideHousing\\Hill_DefGuardA03_patrol",
	
	sHill_DefGuardB01 = "Default\\HillsideHousing\\Hill_DefGuardB01_patrol",
	sHill_DefGuardB02 = "Default\\HillsideHousing\\Hill_DefGuardB02_patrol",
	sHill_DefGuardB03 = "Default\\HillsideHousing\\Hill_DefGuardB03_patrol",
	
	sHill_DefGuardC01 = "Default\\HillsideHousing\\Hill_DefGuardC01_patrol",
	sHill_DefGuardC02 = "Default\\HillsideHousing\\Hill_DefGuardC02_patrol",
	sHill_DefGuardC03 = "Default\\HillsideHousing\\Hill_DefGuardC03_patrol",
	
	sHill_DefGuardD01 = "Default\\HillsideHousing\\Hill_DefGuardD01_patrol",
	sHill_DefGuardD02 = "Default\\HillsideHousing\\Hill_DefGuardD02_patrol",
	sHill_DefGuardD03 = "Default\\HillsideHousing\\Hill_DefGuardD03_patrol",
	
	sHill_DefGuardE01 = "Default\\HillsideHousing\\Hill_DefGuardE01_patrol",
	sHill_DefGuardE02 = "Default\\HillsideHousing\\Hill_DefGuardE02_patrol",
	sHill_DefGuardE03 = "Default\\HillsideHousing\\Hill_DefGuardE03_patrol",
	
--------- Apartments - Ed	
	sAprt_BBCourtA = "Default\\Apartments\\Aprt_BBCourtA_patrol",
	sAprt_BBCourtB = "Default\\Apartments\\Aprt_BBCourtB_patrol",
	sAprt_BBCourtC = "Default\\Apartments\\Aprt_BBCourtC_patrol",
	sAprt_BBCourtD = "Default\\Apartments\\Aprt_BBCourtD_patrol",
	sAprt_BBCourtE = "Default\\Apartments\\Aprt_BBCourtE_patrol",
	sAprt_BBCourtF = "Default\\Apartments\\Aprt_BBCourtF_patrol",
	sAprt_BBCourtG = "Default\\Apartments\\Aprt_BBCourtG_patrol",
	sAprt_BBCourtH = "Default\\Apartments\\Aprt_BBCourtH_patrol",
	sAprt_BBCourtI = "Default\\Apartments\\Aprt_BBCourtI_patrol",
	sAprt_BBCourtJ = "Default\\Apartments\\Aprt_BBCourtJ_patrol",
	sAprt_CarParkA = "Default\\Apartments\\Aprt_CarParkA_patrol",
	sAprt_CarParkB = "Default\\Apartments\\Aprt_CarParkB_patrol",
	sAprt_CarParkC = "Default\\Apartments\\Aprt_CarParkC_patrol",
	sAprt_CarParkD = "Default\\Apartments\\Aprt_CarParkD_patrol",
	sAprt_CarParkE = "Default\\Apartments\\Aprt_CarParkE_patrol",
	sAprt_CarParkF = "Default\\Apartments\\Aprt_CarParkF_patrol",
	sAprt_EntCrtYrdA = "Default\\Apartments\\Aprt_EntCrtYrdA_patrol",
	sAprt_EntCrtYrdB = "Default\\Apartments\\Aprt_EntCrtYrdB_patrol",
	sAprt_EntCrtYrdC = "Default\\Apartments\\Aprt_EntCrtYrdC_patrol",
	sAprt_EntCrtYrdD = "Default\\Apartments\\Aprt_EntCrtYrdD_patrol",
	sAprt_EntCrtYrdE = "Default\\Apartments\\Aprt_EntCrtYrdE_patrol",
	sAprt_EntCrtYrdF = "Default\\Apartments\\Aprt_EntCrtYrdF_patrol",
	sAprt_EntCrtYrdG = "Default\\Apartments\\Aprt_EntCrtYrdG_patrol",
	sAprt_EntCrtYrdH = "Default\\Apartments\\Aprt_EntCrtYrdH_patrol",
	sAprt_EWasteA = "Default\\Apartments\\Aprt_EWasteA_patrol",
	sAprt_EWasteB = "Default\\Apartments\\Aprt_EWasteB_patrol",
	sAprt_EWasteC = "Default\\Apartments\\Aprt_EWasteC_patrol",
	sAprt_EWasteD = "Default\\Apartments\\Aprt_EWasteD_patrol",
	sAprt_EWasteE = "Default\\Apartments\\Aprt_EWasteE_patrol",
	sAprt_MainBuild1flrA = "Default\\Apartments\\Aprt_MainBuild1flrA_patrol",
	sAprt_MainBuild1flrB = "Default\\Apartments\\Aprt_MainBuild1flrB_patrol",
	sAprt_MainBuild2flr = "Default\\Apartments\\Aprt_MainBuild2flr_patrol",
	sAprt_MainBuild3flr = "Default\\Apartments\\Aprt_MainBuild3flr_patrol",
	sAprt_MainBuild4flr = "Default\\Apartments\\Aprt_MainBuild4flr_patrol",
	sAprt_MainBuild5flr = "Default\\Apartments\\Aprt_MainBuild5flr_patrol",
	sAprt_MainCrtYrdA = "Default\\Apartments\\Aprt_MainCrtYrdA_patrol",
	sAprt_MainCrtYrdB = "Default\\Apartments\\Aprt_MainCrtYrdB_patrol",
	sAprt_MainCrtYrdC = "Default\\Apartments\\Aprt_MainCrtYrdC_patrol",
	sAprt_MainCrtYrdD = "Default\\Apartments\\Aprt_MainCrtYrdD_patrol",
	sAprt_MainCrtYrdE = "Default\\Apartments\\Aprt_MainCrtYrdE_patrol",
	sAprt_MainCrtYrdF = "Default\\Apartments\\Aprt_MainCrtYrdF_patrol",
	sAprt_MainRoofNEQuadA = "Default\\Apartments\\Aprt_MainRoofNEQuadA_patrol",
	sAprt_MainRoofNEQuadB = "Default\\Apartments\\Aprt_MainRoofNEQuadB_patrol",
	sAprt_MainRoofNEQuadC = "Default\\Apartments\\Aprt_MainRoofNEQuadC_patrol",
	sAprt_MainRoofNEQuadD = "Default\\Apartments\\Aprt_MainRoofNEQuadD_patrol",
	sAprt_MainRoofSEQuadA = "Default\\Apartments\\Aprt_MainRoofSEQuadA_patrol",
	sAprt_MainRoofSEQuadB = "Default\\Apartments\\Aprt_MainRoofSEQuadB_patrol",
	sAprt_MainRoofSEQuadC = "Default\\Apartments\\Aprt_MainRoofSEQuadC_patrol",
	sAprt_MainRoofSWQuadA = "Default\\Apartments\\Aprt_MainRoofSWQuadA_patrol",
	sAprt_MainRoofSWQuadB = "Default\\Apartments\\Aprt_MainRoofSWQuadB_patrol",
	sAprt_MainRoofSWQuadC = "Default\\Apartments\\Aprt_MainRoofSWQuadC_patrol",
	sAprt_NStreetA = "Default\\Apartments\\Aprt_NStreetA_patrol",
	sAprt_NStreetB = "Default\\Apartments\\Aprt_NStreetB_patrol",
	sAprt_NStreetC = "Default\\Apartments\\Aprt_NStreetC_patrol",
	sAprt_NStreetD = "Default\\Apartments\\Aprt_NStreetD_patrol",
	sAprt_NStreetE = "Default\\Apartments\\Aprt_NStreetE_patrol",
	sAprt_NStreetF = "Default\\Apartments\\Aprt_NStreetF_patrol",
	sAprt_RearCorrA = "Default\\Apartments\\Aprt_RearCorrA_patrol",
	sAprt_RearGateA = "Default\\Apartments\\Aprt_RearGateA_patrol",
	sAprt_SStreetA = "Default\\Apartments\\Aprt_SStreetA_patrol",
	sAprt_SStreetB = "Default\\Apartments\\Aprt_SStreetB_patrol",
	sAprt_SStreetC = "Default\\Apartments\\Aprt_SStreetC_patrol",
	sAprt_SStreetD = "Default\\Apartments\\Aprt_SStreetD_patrol",
	sAprt_SStreetE = "Default\\Apartments\\Aprt_SStreetE_patrol",
	sAprt_SStreetF = "Default\\Apartments\\Aprt_SStreetF_patrol",
	sAprt_Vio_GrnHse = "Default\\Apartments\\Aprt_Vio_GrnHse_patrol",
	sAprt_Vio_Podium = "Default\\Apartments\\Aprt_Vio_Podium_patrol",
	sAprt_Vio_Pool = "Default\\Apartments\\Aprt_Vio_Pool_patrol",
	sAprt_Vio_Safe = "Default\\Apartments\\Aprt_Vio_Safe_patrol",
	sAprt_WWasteA = "Default\\Apartments\\Aprt_WWasteA_patrol",
	sAprt_WWasteB = "Default\\Apartments\\Aprt_WWasteB_patrol",
	sAprt_WWasteC = "Default\\Apartments\\Aprt_WWasteC_patrol",
	sAprt_WWasteD = "Default\\Apartments\\Aprt_WWasteD_patrol",
	sAprt_WWasteE = "Default\\Apartments\\Aprt_WWasteE_patrol",
	sAprt_DSquadA_00 = "Default\\Apartments\\Aprt_DSquadA_00_patrol",
	sAprt_DSquadA_01 = "Default\\Apartments\\Aprt_DSquadA_01_patrol",
	sAprt_DSquadA_02 = "Default\\Apartments\\Aprt_DSquadA_02_patrol",
	sAprt_DSquadA_03 = "Default\\Apartments\\Aprt_DSquadA_03_patrol",	
	sAprt_DSquadB_00 = "Default\\Apartments\\Aprt_DSquadB_00_patrol",
	sAprt_DSquadB_01 = "Default\\Apartments\\Aprt_DSquadB_01_patrol",
	sAprt_DSquadB_02 = "Default\\Apartments\\Aprt_DSquadB_02_patrol",	
	sAprt_DSquadC_00 = "Default\\Apartments\\Aprt_DSquadC_00_patrol",
	sAprt_DSquadC_01 = "Default\\Apartments\\Aprt_DSquadC_01_patrol",
	sAprt_DSquadC_02 = "Default\\Apartments\\Aprt_DSquadC_02_patrol",		
	sAprt_DSquadD_00 = "Default\\Apartments\\Aprt_DSquadD_00_patrol",
	sAprt_DSquadD_01 = "Default\\Apartments\\Aprt_DSquadD_01_patrol",
	sAprt_DSquadD_02 = "Default\\Apartments\\Aprt_DSquadD_02_patrol",				
	sAprt_Roof_00 = "Default\\Apartments\\Aprt_Roof_00_patrol",			
	sAprt_Roof_01 = "Default\\Apartments\\Aprt_Roof_01_patrol",			
	sAprt_Roof_02 = "Default\\Apartments\\Aprt_Roof_02_patrol",			
	sAprt_Roof_03 = "Default\\Apartments\\Aprt_Roof_03_patrol",			
	sAprt_WasteDS_00 = "Default\\Apartments\\Aprt_WasteDS_00_patrol",			
	sAprt_WasteDS_01 = "Default\\Apartments\\Aprt_WasteDS_01_patrol",			
	sAprt_WasteDS_02 = "Default\\Apartments\\Aprt_WasteDS_02_patrol",			
	sAprt_WasteDS_03 = "Default\\Apartments\\Aprt_WasteDS_03_patrol",				
	sAprt_StreetDef_00 = "Default\\Apartments\\Aprt_StreetDef_00_patrol",
	sAprt_StreetDef_01 = "Default\\Apartments\\Aprt_StreetDef_01_patrol",
	sAprt_StreetDef_02 = "Default\\Apartments\\Aprt_StreetDef_02_patrol",
	sAprt_StreetDef_03 = "Default\\Apartments\\Aprt_StreetDef_03_patrol",
	sAprt_EmulateWander00 = "Default\\Apartments\\Aprt_EmulateWander00_patrol",
	
--------- Sports Complex - Ed
	sSprt_BeachA = "Default\\SportsComplex\\Sprt_BeachA_patrol",
	sSprt_BeachB = "Default\\SportsComplex\\Sprt_BeachB_patrol",
	sSprt_BeachC = "Default\\SportsComplex\\Sprt_BeachC_patrol",
	sSprt_BeachD = "Default\\SportsComplex\\Sprt_BeachD_patrol",
	sSprt_BeachE = "Default\\SportsComplex\\Sprt_BeachE_patrol",
	sSprt_BeachF = "Default\\SportsComplex\\Sprt_BeachF_patrol",
	sSprt_BuildBotFlrA = "Default\\SportsComplex\\Sprt_BuildBotFlrA_patrol",
	sSprt_BuildBotFlrB = "Default\\SportsComplex\\Sprt_BuildBotFlrB_patrol",
	sSprt_BuildBotFlrC = "Default\\SportsComplex\\Sprt_BuildBotFlrC_patrol",
	sSprt_BuildEntA = "Default\\SportsComplex\\Sprt_BuildEntA_patrol",
	sSprt_BuildEntB = "Default\\SportsComplex\\Sprt_BuildEntB_patrol",
	sSprt_BuildEntC = "Default\\SportsComplex\\Sprt_BuildEntC_patrol",
	sSprt_BuildEntD = "Default\\SportsComplex\\Sprt_BuildEntD_patrol",
	sSprt_BuildEntE = "Default\\SportsComplex\\Sprt_BuildEntE_patrol",
	sSprt_BuildMidFlrA = "Default\\SportsComplex\\Sprt_BuildMidFlrA_patrol",
	sSprt_BuildMidFlrB = "Default\\SportsComplex\\Sprt_BuildMidFlrB_patrol",
	sSprt_BuildMidFlrC = "Default\\SportsComplex\\Sprt_BuildMidFlrC_patrol",
	sSprt_BuildTopFlrA = "Default\\SportsComplex\\Sprt_BuildTopFlrA_patrol",
	sSprt_ECarParkA = "Default\\SportsComplex\\Sprt_ECarParkA_patrol",
	sSprt_ECarParkB = "Default\\SportsComplex\\Sprt_ECarParkB_patrol",
	sSprt_FightZoneA = "Default\\SportsComplex\\Sprt_FightZoneA_patrol",
	sSprt_FightZoneB = "Default\\SportsComplex\\Sprt_FightZoneB_patrol",
	sSprt_FightZoneC = "Default\\SportsComplex\\Sprt_FightZoneC_patrol",
	sSprt_FightZoneD = "Default\\SportsComplex\\Sprt_FightZoneD_patrol",
	sSprt_FightZoneE = "Default\\SportsComplex\\Sprt_FightZoneE_patrol",
	sSprt_FightZoneF = "Default\\SportsComplex\\Sprt_FightZoneF_patrol",
	sSprt_FightZoneG = "Default\\SportsComplex\\Sprt_FightZoneG_patrol",
	sSprt_FightZoneH = "Default\\SportsComplex\\Sprt_FightZoneH_patrol",
	sSprt_GymZoneA = "Default\\SportsComplex\\Sprt_GymZoneA_patrol",
	sSprt_GymZoneB = "Default\\SportsComplex\\Sprt_GymZoneB_patrol",
	sSprt_GymZoneC = "Default\\SportsComplex\\Sprt_GymZoneC_patrol",
	sSprt_GymZoneD = "Default\\SportsComplex\\Sprt_GymZoneD_patrol",
	sSprt_GymZoneE = "Default\\SportsComplex\\Sprt_GymZoneE_patrol",
	sSprt_GymZoneF = "Default\\SportsComplex\\Sprt_GymZoneF_patrol",
	sSprt_Pat_GymZone00 = "Default\\SportsComplex\\Sprt_Pat_GymZone00_patrol",
	sSprt_Pat_PoolZone00 = "Default\\SportsComplex\\Sprt_Pat_PoolZone00_patrol",
	sSprt_Pat_FightZone00 = "Default\\SportsComplex\\Sprt_Pat_FightZone00_patrol",
	sSprt_PoolsA = "Default\\SportsComplex\\Sprt_PoolsA_patrol",
	sSprt_PoolsB = "Default\\SportsComplex\\Sprt_PoolsB_patrol",
	sSprt_PoolsC = "Default\\SportsComplex\\Sprt_PoolsC_patrol",
	sSprt_PoolsD = "Default\\SportsComplex\\Sprt_PoolsD_patrol",
	sSprt_PoolsE = "Default\\SportsComplex\\Sprt_PoolsE_patrol",
	sSprt_PoolsF = "Default\\SportsComplex\\Sprt_PoolsF_patrol",
	sSprt_PoolsG = "Default\\SportsComplex\\Sprt_PoolsG_patrol",	
	sSprt_PoolSniperA = "Default\\SportsComplex\\Sprt_PoolSniperA_patrol",
	sSprt_Rod_GymZone00 = "Default\\SportsComplex\\Sprt_Rod_GymZone00_patrol",
	sSprt_Rod_SafeZone00 = "Default\\SportsComplex\\Sprt_Rod_SafeZone00_patrol",
	sSprt_Rod_FightZone00 = "Default\\SportsComplex\\Sprt_Rod_FightZone00_patrol",	
	sSprt_RunTrackA = "Default\\SportsComplex\\Sprt_RunTrackA_patrol",
	sSprt_RunTrackB = "Default\\SportsComplex\\Sprt_RunTrackB_patrol",
	sSprt_RunTrackC = "Default\\SportsComplex\\Sprt_RunTrackC_patrol",	
	sSprt_TCourtsA = "Default\\SportsComplex\\Sprt_TCourtsA_patrol",
	sSprt_TCourtsB = "Default\\SportsComplex\\Sprt_TCourtsB_patrol",
	sSprt_TCourtsC = "Default\\SportsComplex\\Sprt_TCourtsC_patrol",
	sSprt_TCourtsD = "Default\\SportsComplex\\Sprt_TCourtsD_patrol",
	sSprt_TCourtsE = "Default\\SportsComplex\\Sprt_TCourtsE_patrol",
	sSprt_TCourtsF = "Default\\SportsComplex\\Sprt_TCourtsF_patrol",
	sSprt_TCourtsG = "Default\\SportsComplex\\Sprt_TCourtsG_patrol",
	sSprt_TCourtsH = "Default\\SportsComplex\\Sprt_TCourtsH_patrol",
	sSprt_TCourtsI = "Default\\SportsComplex\\Sprt_TCourtsI_patrol",
	sSprt_WCarParkA = "Default\\SportsComplex\\Sprt_WCarParkA_patrol",
	sSprt_WCarParkB = "Default\\SportsComplex\\Sprt_WCarParkB_patrol",
	sSprt_WCarParkC = "Default\\SportsComplex\\Sprt_WCarParkC_patrol",
	sSprt_WCarParkD = "Default\\SportsComplex\\Sprt_WCarParkD_patrol",
	sSprt_WCarParkE = "Default\\SportsComplex\\Sprt_WCarParkE_patrol",
 	sSprt_CarParkEntA = "Default\\SportsComplex\\Sprt_CarParkEntA_patrol",
 	sSprt_CarParkEntB = "Default\\SportsComplex\\Sprt_CarParkEntB_patrol",	
 	sSprt_VictorA = "Default\\SportsComplex\\Sprt_VictorA_patrol",
 	sSprt_VictorB = "Default\\SportsComplex\\Sprt_VictorB_patrol",	 	
 	sSprt_Rod_Entrance00 = "Default\\SportsComplex\\Sprt_Rod_Entrance00_patrol",
 	sSprt_CliffWatchA = "Default\\SportsComplex\\Sprt_CliffWatchA_patrol",
 	sSprt_CliffWatchB = "Default\\SportsComplex\\Sprt_CliffWatchB_patrol",
 	sSprt_CliffWatchC = "Default\\SportsComplex\\Sprt_CliffWatchC_patrol", 	
 	sSprt_CliffSniperA = "Default\\SportsComplex\\Sprt_CliffSniperA_patrol", 	 	
 	sSprt_CliffA = "Default\\SportsComplex\\Sprt_CliffA_patrol", 	 	 	
 	sSprt_CliffB = "Default\\SportsComplex\\Sprt_CliffB_patrol",
	sSprt_FightCrowd_00 = "Default\\SportsComplex\\Sprt_FightCrowd_00_patrol",	 	
	sSprt_FightCrowd_01 = "Default\\SportsComplex\\Sprt_FightCrowd_01_patrol",	 		
	sSprt_FightCrowd_02 = "Default\\SportsComplex\\Sprt_FightCrowd_02_patrol",	 		
	sSprt_FightCrowd_03 = "Default\\SportsComplex\\Sprt_FightCrowd_03_patrol",	 		
	sSprt_FightCrowd_04 = "Default\\SportsComplex\\Sprt_FightCrowd_04_patrol",	 		
	sSprt_FightCrowd_05 = "Default\\SportsComplex\\Sprt_FightCrowd_05_patrol",	 		
	sSprt_FightCrowd_06 = "Default\\SportsComplex\\Sprt_FightCrowd_06_patrol",	 		
	sSprt_FightCrowd_07 = "Default\\SportsComplex\\Sprt_FightCrowd_07_patrol",	 		
	sSprt_FightCrowd_08 = "Default\\SportsComplex\\Sprt_FightCrowd_08_patrol",	 		
	sSprt_FightCrowd_09 = "Default\\SportsComplex\\Sprt_FightCrowd_09_patrol",	 		
	sSprt_FightCrowd_10 = "Default\\SportsComplex\\Sprt_FightCrowd_10_patrol",	 		
	sSprt_FightCrowd_11 = "Default\\SportsComplex\\Sprt_FightCrowd_11_patrol",	 		
	sSprt_FightCrowd_12 = "Default\\SportsComplex\\Sprt_FightCrowd_12_patrol",	 		
	sSprt_FightCrowd_13 = "Default\\SportsComplex\\Sprt_FightCrowd_13_patrol",	 		
	sSprt_FightCrowd_14 = "Default\\SportsComplex\\Sprt_FightCrowd_14_patrol",	 		
	sSprt_FightCrowd_15 = "Default\\SportsComplex\\Sprt_FightCrowd_15_patrol",	 		
	sSprt_FightCrowd_16 = "Default\\SportsComplex\\Sprt_FightCrowd_16_patrol",	 		
	sSprt_FightCrowd_17 = "Default\\SportsComplex\\Sprt_FightCrowd_17_patrol",	 			
	sSprt_FightCrowd_18 = "Default\\SportsComplex\\Sprt_FightCrowd_18_patrol",	 				
	sSprt_FightCrowd_19 = "Default\\SportsComplex\\Sprt_FightCrowd_19_patrol",	
	sSprt_SafeBG_00 = "Default\\SportsComplex\\Sprt_SafeBG_00_patrol",	
	sSprt_SafeBG_01 = "Default\\SportsComplex\\Sprt_SafeBG_01_patrol",	
	sSprt_SafeBG_02 = "Default\\SportsComplex\\Sprt_SafeBG_02_patrol",	
	sSprt_SafeBG_03 = "Default\\SportsComplex\\Sprt_SafeBG_03_patrol",	
	sSprt_Def00 = "Default\\SportsComplex\\Sprt_Def00_patrol",		
	sSprt_Def01 = "Default\\SportsComplex\\Sprt_Def01_patrol",		
	sSprt_Def02 = "Default\\SportsComplex\\Sprt_Def02_patrol",		
	sSprt_Def03 = "Default\\SportsComplex\\Sprt_Def03_patrol",		
	sSprt_Def04 = "Default\\SportsComplex\\Sprt_Def04_patrol",		
	sSprt_Def05 = "Default\\SportsComplex\\Sprt_Def05_patrol",		
	sSprt_Def06 = "Default\\SportsComplex\\Sprt_Def06_patrol",		
	sSprt_Def07 = "Default\\SportsComplex\\Sprt_Def07_patrol",				
 	sSprt_Seed_00 = "Default\\SportsComplex\\Sprt_Seed_00_patrol",	
 	sSprt_Seed_01 = "Default\\SportsComplex\\Sprt_Seed_01_patrol",	

--------- Intel Complex - Ed
	sCInt_BoothA = "Default\\IntelComplex\\CInt_BoothA_patrol",
	sCInt_DomeAppEstA = "Default\\IntelComplex\\CInt_DomeAppEstA_patrol",
	sCInt_DomeAppEstB = "Default\\IntelComplex\\CInt_DomeAppEstB_patrol",
	sCInt_DomeAppWstA = "Default\\IntelComplex\\CInt_DomeAppWstA_patrol",
	sCInt_DomeAppWstB = "Default\\IntelComplex\\CInt_DomeAppWstB_patrol",
	sCInt_DomeAppWstC = "Default\\IntelComplex\\CInt_DomeAppWstC_patrol",
	sCInt_DomeAppWstD = "Default\\IntelComplex\\CInt_DomeAppWstD_patrol",
	sCInt_DomeLowA = "Default\\IntelComplex\\CInt_DomeLowA_patrol",
	sCInt_DomeLowB = "Default\\IntelComplex\\CInt_DomeLowB_patrol",
	sCInt_DomeMidA = "Default\\IntelComplex\\CInt_DomeMidA_patrol",
	sCInt_DomeMidB = "Default\\IntelComplex\\CInt_DomeMidB_patrol",
	sCInt_DomeUpA = "Default\\IntelComplex\\CInt_DomeUpA_patrol",
	sCInt_DomeUpB = "Default\\IntelComplex\\CInt_DomeUpB_patrol",
	sCInt_EntCrtYrdA = "Default\\IntelComplex\\CInt_EntCrtYrdA_patrol",
	sCInt_EntCrtYrdB = "Default\\IntelComplex\\CInt_EntCrtYrdB_patrol",
	sCInt_EntCrtYrdC = "Default\\IntelComplex\\CInt_EntCrtYrdC_patrol",
	sCInt_EntCrtYrdD = "Default\\IntelComplex\\CInt_EntCrtYrdD_patrol",
	sCInt_EntCrtYrdE = "Default\\IntelComplex\\CInt_EntCrtYrdE_patrol",
	sCInt_EntCrtYrdF = "Default\\IntelComplex\\CInt_EntCrtYrdF_patrol",
	sCInt_EntCrtYrdG = "Default\\IntelComplex\\CInt_EntCrtYrdG_patrol",
	sCInt_EntCrtYrdH = "Default\\IntelComplex\\CInt_EntCrtYrdH_patrol",
	sCInt_EntCrtYrdI = "Default\\IntelComplex\\CInt_EntCrtYrdI_patrol",
	sCInt_EntCrtYrdJ = "Default\\IntelComplex\\CInt_EntCrtYrdJ_patrol",
	sCInt_InnrCrtYrdLowA = "Default\\IntelComplex\\CInt_InnrCrtYrdLowA_patrol",
	sCInt_InnrCrtYrdLowB = "Default\\IntelComplex\\CInt_InnrCrtYrdLowB_patrol",
	sCInt_InnrCrtYrdLowC = "Default\\IntelComplex\\CInt_InnrCrtYrdLowC_patrol",
	sCInt_InnrCrtYrdLowD = "Default\\IntelComplex\\CInt_InnrCrtYrdLowD_patrol",
	sCInt_InnrCrtYrdUpA = "Default\\IntelComplex\\CInt_InnrCrtYrdUpA_patrol",
	sCInt_InnrCrtYrdUpB = "Default\\IntelComplex\\CInt_InnrCrtYrdUpB_patrol",
	sCInt_OutWalkWayA = "Default\\IntelComplex\\CInt_OutWalkWayA_patrol",
	sCInt_OutWalkWayB = "Default\\IntelComplex\\CInt_OutWalkWayB_patrol",
	sCInt_OutWalkWayC = "Default\\IntelComplex\\CInt_OutWalkWayC_patrol",
	sCInt_OutWalkWayD = "Default\\IntelComplex\\CInt_OutWalkWayD_patrol",
	sCInt_RadChambBaseA = "Default\\IntelComplex\\CInt_RadChambBaseA_patrol",
	sCInt_RadChambBaseB = "Default\\IntelComplex\\CInt_RadChambBaseB_patrol",
	sCInt_RadChambBaseC = "Default\\IntelComplex\\CInt_RadChambBaseC_patrol",
	sCInt_RadChambFirstA = "Default\\IntelComplex\\CInt_RadChambFirstA_patrol",
	sCInt_RadChambRoofA = "Default\\IntelComplex\\CInt_RadChambRoofA_patrol",
	sCInt_RadChambRoofB = "Default\\IntelComplex\\CInt_RadChambRoofB_patrol",
	sCInt_RadChambRoofC = "Default\\IntelComplex\\CInt_RadChambRoofC_patrol",
	sCInt_RadChambSecA = "Default\\IntelComplex\\CInt_RadChambSecA_patrol",
	sCInt_RadChambSecB = "Default\\IntelComplex\\CInt_RadChambSecB_patrol",
	sCInt_RadChambSecC = "Default\\IntelComplex\\CInt_RadChambSecC_patrol",
	sCInt_RadChambSecD = "Default\\IntelComplex\\CInt_RadChambSecD_patrol",
	sCInt_RadChambSecE = "Default\\IntelComplex\\CInt_RadChambSecE_patrol",

--------- Refinery - Ed
	sRef_GPostA_00 = "Default\\Refinery\\Ref_GPostA_00_patrol",
	sRef_GPostA_01 = "Default\\Refinery\\Ref_GPostA_01_patrol",
	sRef_GPostA_02 = "Default\\Refinery\\Ref_GPostA_02_patrol",
	sRef_GPostB_00 = "Default\\Refinery\\Ref_GPostB_00_patrol",	
	sRef_GPostB_01 = "Default\\Refinery\\Ref_GPostB_01_patrol",	
	sRef_GPostB_02 = "Default\\Refinery\\Ref_GPostB_02_patrol",	
	sRef_BBuild_00 = "Default\\Refinery\\Ref_BBuild_00_patrol",	
	sRef_BBuild_01 = "Default\\Refinery\\Ref_BBuild_01_patrol",		
	sRef_BBuild_02 = "Default\\Refinery\\Ref_BBuild_02_patrol",		
	sRef_BossPatrolFlr_0 = "Default\\Refinery\\Ref_BossPatrolFlr_0_patrol",		
	sRef_BossPatrolFlr_1 = "Default\\Refinery\\Ref_BossPatrolFlr_1_patrol",			
	sRef_BossPatrolFlr_2 = "Default\\Refinery\\Ref_BossPatrolFlr_2_patrol",			
	sRef_CenStrucFlr1_00 = "Default\\Refinery\\Ref_CenStrucFlr1_00_patrol",
	sRef_CenStrucFlr1_01 = "Default\\Refinery\\Ref_CenStrucFlr1_01_patrol",
	sRef_CenStrucFlr1_02 = "Default\\Refinery\\Ref_CenStrucFlr1_02_patrol",
	sRef_CenStrucFlr1_03 = "Default\\Refinery\\Ref_CenStrucFlr1_03_patrol",
	sRef_CenStrucFlr2_00 = "Default\\Refinery\\Ref_CenStrucFlr2_00_patrol",
	sRef_CenStrucFlr2_01 = "Default\\Refinery\\Ref_CenStrucFlr2_01_patrol",
	sRef_CenStrucFlr2_02 = "Default\\Refinery\\Ref_CenStrucFlr2_02_patrol",
	sRef_CenStrucFlr2_03 = "Default\\Refinery\\Ref_CenStrucFlr2_03_patrol",	
	sRef_CenStrucFlr3_00 = "Default\\Refinery\\Ref_CenStrucFlr3_00_patrol",
	sRef_CenStrucFlr3_01 = "Default\\Refinery\\Ref_CenStrucFlr3_01_patrol",
	sRef_CenStrucFlr3_02 = "Default\\Refinery\\Ref_CenStrucFlr3_02_patrol",
	sRef_CenStrucFlr3_03 = "Default\\Refinery\\Ref_CenStrucFlr3_03_patrol",
	sRef_CenStrucFlr4_00 = "Default\\Refinery\\Ref_CenStrucFlr4_00_patrol",
	sRef_CenStrucFlr4_01 = "Default\\Refinery\\Ref_CenStrucFlr4_01_patrol",
	sRef_CenStrucFlr4_02 = "Default\\Refinery\\Ref_CenStrucFlr4_02_patrol",
	sRef_CenStrucFlr4_03 = "Default\\Refinery\\Ref_CenStrucFlr4_03_patrol",	
	sRef_CenStrucFlr5_00 = "Default\\Refinery\\Ref_CenStrucFlr5_00_patrol",
	sRef_CenStrucFlr5_01 = "Default\\Refinery\\Ref_CenStrucFlr5_01_patrol",
	sRef_CenStrucFlr5_02 = "Default\\Refinery\\Ref_CenStrucFlr5_02_patrol",
	sRef_CenStrucFlr5_03 = "Default\\Refinery\\Ref_CenStrucFlr5_03_patrol",	
	sRef_PipeWalks_00 = "Default\\Refinery\\Ref_PipeWalks_00_patrol",		
	sRef_PipeWalks_01 = "Default\\Refinery\\Ref_PipeWalks_01_patrol",			
	sRef_PipeWalks_02 = "Default\\Refinery\\Ref_PipeWalks_02_patrol",			
	sRef_PipeWalks_03 = "Default\\Refinery\\Ref_PipeWalks_03_patrol",		
	sRef_PipeWalks_04 = "Default\\Refinery\\Ref_PipeWalks_04_patrol",
	sRef_WorkerA = "Default\\Refinery\\Ref_WorkerA_patrol",
	
--------- Garage - Neil
	sGarageHillside1 = "Default\\Garage\\GAHillside1_patrol",
	sGarageHillside2 = "Default\\Garage\\GAHillside2_patrol",
	sGarageHillside3 = "Default\\Garage\\GAHillside3_patrol",
	
	sGarageBackWallBalcony = "Default\\Garage\\GABackWallBalcony_patrol",
	sGarageBackWallBalcony1 = "Default\\Garage\\GABackWallBalcony1_patrol",
	
	sGarageFrontWallBalcony = "Default\\Garage\\GAFrontWallBalcony_patrol",
	sGarageFrontWallBalcony1 = "Default\\Garage\\GAFrontWallBalcony1_patrol",
	
	sGarageNorthBalcony = "Default\\Garage\\GANorthBalcony_patrol",
	sGarageNorthBalcony1 = "Default\\Garage\\GANorthBalcony1_patrol",
	
	sGarageSouthBalcony = "Default\\Garage\\GASouthBalcony_patrol",
	
	sGarageGantry1 = "Default\\Garage\\GAGantry1_patrol",
	sGarageGantry2 = "Default\\Garage\\GAGantry2_patrol",
	sGarageGantry3 = "Default\\Garage\\GAGantry3_patrol",
	
	sGarageRearRoof0 = "Default\\Garage\\GARearRoof_patrol",
	sGarageRearRoof1 = "Default\\Garage\\GARearRoof1_patrol",
	sGarageRearRoof2 = "Default\\Garage\\GARearRoof2_patrol",
	sGarageRearRoof3 = "Default\\Garage\\GARearRoof3_patrol",
	
	sGarageBossRoom1 = "Default\\Garage\\GABossRoom1_patrol",
	sGarageBossRoom2 = "Default\\Garage\\GABossRoom2_patrol",
	
	sGarageMechanicsGarage1 = "Default\\Garage\\GAMechanicsGarage1_patrol",
	sGarageMechanicsGarage2 = "Default\\Garage\\GAMechanicsGarage2_patrol",
	
	sGarageFrontDoor1 = "Default\\Garage\\GAFrontDoor1_patrol",
	sGarageFrontDoor2 = "Default\\Garage\\GAFrontDoor2_patrol",
	
	
--------- Lighthouse - Northy
	sLight_Beach1 = "Default\\Lighthouse\\L_Beach1_patrol",
	sLight_Beach2 = "Default\\Lighthouse\\L_Beach2_patrol",
	sLight_Bridge1 = "Default\\Lighthouse\\L_Bridge1_patrol",
	sLight_Bridge2 = "Default\\Lighthouse\\L_Bridge2_patrol",
	sLight_CaveFloor1 = "Default\\Lighthouse\\L_CaveFloor1_patrol",
	sLight_CaveFloor2 = "Default\\Lighthouse\\L_CaveFloor2_patrol",
	sLight_CaveFloor3 = "Default\\Lighthouse\\L_CaveFloor3_patrol",
	sLight_CaveFloor4 = "Default\\Lighthouse\\L_CaveFloor4_patrol",
	sLight_CaveTunnel1 = "Default\\Lighthouse\\L_CaveTunnel1_patrol",
	sLight_CaveTunnel2 = "Default\\Lighthouse\\L_CaveTunnel2_patrol",
	sLight_CaveWalkway1 = "Default\\Lighthouse\\L_CaveWalkway1_patrol",
	sLight_Cliff1 = "Default\\Lighthouse\\L_Cliff1_patrol",
	sLight_Cliff2 = "Default\\Lighthouse\\L_Cliff2_patrol",
	sLight_Cliff3 = "Default\\Lighthouse\\L_Cliff3_patrol",
	sLight_Cliff4 = "Default\\Lighthouse\\L_Cliff4_patrol",
	sLight_Cliffside1 = "Default\\Lighthouse\\L_Cliffside1_patrol",
	sLight_ElevatorPlatform = "Default\\Lighthouse\\L_ElevatorPlatform_patrol",
	sLight_Forest1 = "Default\\Lighthouse\\L_Forest1_patrol",
	sLight_Forest2 = "Default\\Lighthouse\\L_Forest2_patrol",
	sLight_L_Gate1 = "Default\\Lighthouse\\L_Gate1_patrol",
	sLight_L_Gate2 = "Default\\Lighthouse\\L_Gate2_patrol",
	sLight_LighthouseBase1 = "Default\\Lighthouse\\L_LighthouseBase1_patrol",
	sLight_LighthouseBase2 = "Default\\Lighthouse\\L_LighthouseBase2_patrol",
	sLight_LighthouseBase3 = "Default\\Lighthouse\\L_LighthouseBase3_patrol",
	
--------- Radio Station - Northy
	sRadio_FrontWall1 = "Default\\Radio\\RS_FrontWall1_patrol",
	sRadio_Ground1 = "Default\\Radio\\RS_Ground1_patrol",
	sRadio_Ground2 = "Default\\Radio\\RS_Ground2_patrol",
	sRadio_HillPath = "Default\\Radio\\RS_HillPath_patrol",
	sRadio_Roof1 = "Default\\Radio\\RS_Roof1_patrol",
	sRadio_Roof2 = "Default\\Radio\\RS_Roof2_patrol",
	sRadio_Stairs1 = "Default\\Radio\\RS_Stairs1_patrol",
	sRadio_Stairs2 = "Default\\Radio\\RS_Stairs2_patrol",
	sRadio_Stairs3 = "Default\\Radio\\RS_Stairs3_patrol",
	sRadio_Tunnel1 = "Default\\Radio\\RS_Tunnel1_patrol",
	
--------- Transport Depot - Northy
	sTrans_Container1 = "Default\\Transport\\TD_Container1_patrol",
	sTrans_Corridor1 = "Default\\Transport\\TD_Corridor1_patrol",
	sTrans_Corridor2 = "Default\\Transport\\TD_Corridor2_patrol",
	sTrans_Corridor3 = "Default\\Transport\\TD_Corridor3_patrol",
	sTrans_EntryPlatform1 = "Default\\Transport\\TD_EntryPlatform1_patrol",
	sTrans_EntryPlatform2 = "Default\\Transport\\TD_EntryPlatform2_patrol",
	sTrans_EntryPlatform3 = "Default\\Transport\\TD_EntryPlatform3_patrol",
	sTrans_FrontDoor1 = "Default\\Transport\\TD_FrontDoor1_patrol",
	sTrans_GuardTower1 = "Default\\Transport\\TD_GuardTower1_patrol",
	sTrans_GuardTower2 = "Default\\Transport\\TD_GuardTower2_patrol",
	sTrans_GuardTower3 = "Default\\Transport\\TD_GuardTower3_patrol",
	sTrans_LargeWareEntrance1 = "Default\\Transport\\TD_LargeWareEntrance1_patrol",
	sTrans_LoadingBay1 = "Default\\Transport\\TD_LoadingBay1_patrol",
	sTrans_LoadingBay2 = "Default\\Transport\\TD_LoadingBay2_patrol",
	sTrans_LoadingBay3 = "Default\\Transport\\TD_LoadingBay3_patrol",
	sTrans_MainRoof2 = "Default\\Transport\\TD_MainRoof2_patrol",
	sTrans_MainRoof3 = "Default\\Transport\\TD_MainRoof3_patrol",
	sTrans_MainWare1 = "Default\\Transport\\TD_MainWare1_patrol",
	sTrans_MainWare2 = "Default\\Transport\\TD_MainWare2_patrol",
	sTrans_SecureWareDoor1 = "Default\\Transport\\TD_SecureWareDoor1_patrol",
	sTrans_SecureWareDoor2 = "Default\\Transport\\TD_SecureWareDoor2_patrol",
	sTrans_SecureWareDoor3 = "Default\\Transport\\TD_SecureWareDoor3_patrol",
	sTrans_SecureWareDoor4 = "Default\\Transport\\TD_SecureWareDoor4_patrol",
	
--------- Security Complex - Northy
	sSecure_Basement1 = "Default\\Security\\SC_Basement1_patrol",
	sSecure_Basement2 = "Default\\Security\\SC_Basement2_patrol",
	sSecure_Docks1 = "Default\\Security\\SC_Docks1_patrol",
	sSecure_Docks2 = "Default\\Security\\SC_Docks2_patrol",
	sSecure_Docks3 = "Default\\Security\\SC_Docks3_patrol",
	sSecure_FacadeRoom1 = "Default\\Security\\SC_FacadeRoom1_patrol",
	sSecure_FacadeRoom2 = "Default\\Security\\SC_FacadeRoom2_patrol",
	sSecure_Middle1 = "Default\\Security\\SC_Middle1_patrol",
	sSecure_MiddleOut1 = "Default\\Security\\SC_MiddleOut1_patrol",
	sSecure_MiddleOut2 = "Default\\Security\\SC_MiddleOut2_patrol",
	sSecure_MiddleOut3 = "Default\\Security\\SC_MiddleOut3_patrol",
	sSecure_MiddleOut4 = "Default\\Security\\SC_MiddleOut4_patrol",
	sSecure_OuterLedge1 = "Default\\Security\\SC_OuterLedge1_patrol",
	sSecure_OuterLedge2 = "Default\\Security\\SC_OuterLedge2_patrol",
	sSecure_OuterLedge3 = "Default\\Security\\SC_OuterLedge3_patrol",
	sSecure_OuterLedge4 = "Default\\Security\\SC_OuterLedge4_patrol",
	sSecure_Roof1 = "Default\\Security\\SC_Roof1_patrol",
	sSecure_Roof2 = "Default\\Security\\SC_Roof2_patrol",
	sSecure_Roof3 = "Default\\Security\\SC_Roof3_patrol",
	sSecure_Roof4 = "Default\\Security\\SC_Roof4_patrol",
	sSecure_Roof5 = "Default\\Security\\SC_Roof5_patrol",
	sSecure_RoofStairs1 = "Default\\Security\\SC_RoofStairs1_patrol",
	sSecure_RoofStairs2 = "Default\\Security\\SC_RoofStairs2_patrol",
	sSecure_RoofStairs3 = "Default\\Security\\SC_RoofStairs3_patrol",
	sSecure_Stairs1 = "Default\\Security\\SC_Stairs1_patrol",
	
--------- Additional Rooftops - Ed		

	sAdd_Rooftop00 = "Default\\Rooftops\\Add_Rooftop00_patrol",
	sAdd_Rooftop01 = "Default\\Rooftops\\Add_Rooftop01_patrol",
	sAdd_Rooftop02 = "Default\\Rooftops\\Add_Rooftop02_patrol",
	sAdd_Rooftop03 = "Default\\Rooftops\\Add_Rooftop03_patrol",
	sAdd_Rooftop04 = "Default\\Rooftops\\Add_Rooftop04_patrol",	
    
--------- Docks - Russ

    sDock_Maingate1_patrol = "Default\\Docks\\Dock_Maingate1_patrol",
    sDock_Maingate_patrol = "Default\\Docks\\Dock_Maingate_patrol",
    sDock_NewBuild1_patrol = "Default\\Docks\\Dock_NewBuild1_patrol",
    sDock_NewBuild_patrol = "Default\\Docks\\Dock_NewBuild_patrol",
    sDock_Container_PropShot_patrol = "Default\\Docks\\Dock_Container_PropShot_patrol",
    sDock_Container_PropShot_1_patrol = "Default\\Docks\\Dock_Container_PropShot_1_patrol",
    sDock_Container_PropShot_2_patrol = "Default\\Docks\\Dock_Container_PropShot_2_patrol",
    sDock_Blockade_1_1_patrol = "Default\\Docks\\Dock_Blockade_1_1_patrol",
    sDock_Blockade_1_2_patrol = "Default\\Docks\\Dock_Blockade_1_2_patrol",
    sDock_Blockade_1_3_patrol = "Default\\Docks\\Dock_Blockade_1_3_patrol",
    sDock_Blockade_1_4_patrol = "Default\\Docks\\Dock_Blockade_1_4_patrol",
    sDock_Blockade_1_5_patrol = "Default\\Docks\\Dock_Blockade_1_5_patrol",
    sDock_Blockade_1_6_patrol = "Default\\Docks\\Dock_Blockade_1_6_patrol",   
    sDock_Blockade_2_1_patrol = "Default\\Docks\\Dock_Blockade_2_1_patrol",
    sDock_Blockade_2_2_patrol = "Default\\Docks\\Dock_Blockade_2_2_patrol",
    sDock_Blockade_2_3_patrol = "Default\\Docks\\Dock_Blockade_2_3_patrol",
    sDock_Blockade_2_4_patrol = "Default\\Docks\\Dock_Blockade_2_4_patrol",
    sDock_Blockade_2_5_patrol = "Default\\Docks\\Dock_Blockade_2_5_patrol",
    sDock_Blockade_2_6_patrol = "Default\\Docks\\Dock_Blockade_2_6_patrol",
    sDock_Ware_1_patrol = "Default\\Docks\\Dock_Ware_1_patrol", 
    sDock_Ware_1_1_patrol = "Default\\Docks\\Dock_Ware_1_1_patrol", 
    sDock_Ware_2_patrol = "Default\\Docks\\Dock_Ware_2_patrol",
    sDock_Ware_2_1_patrol = "Default\\Docks\\Dock_Ware_2_1_patrol",
    sDock_Ware_3_patrol = "Default\\Docks\\Dock_Ware_3_patrol",
    sDock_Ware_3_1_patrol = "Default\\Docks\\Dock_Ware_3_1_patrol",
    sDock_Ware_3_2_patrol = "Default\\Docks\\Dock_Ware_3_2_patrol",
    sDock_Ware_3_3_patrol = "Default\\Docks\\Dock_Ware_3_3_patrol",
    sDock_Ware_4_patrol = "Default\\Docks\\Dock_Ware_4_patrol",
    sDock_Ware_5_patrol = "Default\\Docks\\Dock_Ware_5_patrol",
    sDock_Defender_1_1_patrol = "Default\\Docks\\Dock_Defender_1_1_patrol",
    sDock_Defender_1_2_patrol = "Default\\Docks\\Dock_Defender_1_2_patrol",
    sDock_Defender_1_3_patrol = "Default\\Docks\\Dock_Defender_1_3_patrol",   
    sDock_Defender_2_1_patrol = "Default\\Docks\\Dock_Defender_2_1_patrol",
    sDock_Defender_2_2_patrol = "Default\\Docks\\Dock_Defender_2_2_patrol",
    sDock_Defender_2_3_patrol = "Default\\Docks\\Dock_Defender_2_3_patrol",  
    sDock_Defender_2_1_patrol = "Default\\Docks\\Dock_Defender_3_1_patrol",
    sDock_Defender_2_2_patrol = "Default\\Docks\\Dock_Defender_3_2_patrol",
    sDock_Defender_2_3_patrol = "Default\\Docks\\Dock_Defender_3_3_patrol",      
    -- delete these 2 at a later date as not used except for graph generation
    sDock_Ship1_patrol = "Default\\Docks\\Dock_Ship1_patrol",
    sDock_Ship2_patrol = "Default\\Docks\\Dock_Ship2_patrol",

--------- Lighthouse - Steve 

	sLimaA = "Default\\Lighthouse\\LH_LimaA_patrol",
	sLimaB = "Default\\Lighthouse\\LH_LimaB_patrol",
	sLimaC = "Default\\Lighthouse\\LH_LimaC_patrol",
	sLimaD = "Default\\Lighthouse\\LH_LimaD_patrol",
	sLimaE = "Default\\Lighthouse\\LH_LimaE_patrol",
	sLimaF = "Default\\Lighthouse\\LH_LimaF_patrol",
	
	LHAlpha01 = "Default\\Lighthouse\\LH_Alpha_01_patrol",
	LHAlpha02 = "Default\\Lighthouse\\LH_Alpha_02_patrol",
	LHAlpha03 = "Default\\Lighthouse\\LH_Alpha_03_patrol",
	LHAlpha04 = "Default\\Lighthouse\\LH_Alpha_04_patrol",

	LHBravo01 = "Default\\Lighthouse\\LH_Bravo_01_patrol",
	LHBravo02 = "Default\\Lighthouse\\LH_Bravo_02_patrol",
	LHBravo03 = "Default\\Lighthouse\\LH_Bravo_03_patrol",

	LHCharlie01 = "Default\\Lighthouse\\LH_Charlie_01_patrol",
	LHCharlie02 = "Default\\Lighthouse\\LH_Charlie_02_patrol",
	LHCharlie03 = "Default\\Lighthouse\\LH_Charlie_03_patrol",

	LHDelta01 = "Default\\Lighthouse\\LH_Delta_01_patrol",
	LHDelta02 = "Default\\Lighthouse\\LH_Delta_02_patrol",
	LHDelta03 = "Default\\Lighthouse\\LH_Delta_03_patrol",

	LHEcho01 = "Default\\Lighthouse\\LH_Echo_01_patrol",
	LHEcho02 = "Default\\Lighthouse\\LH_Echo_02_patrol",
	LHEcho03 = "Default\\Lighthouse\\LH_Echo_03_patrol",

	LHHotel01 = "Default\\Lighthouse\\LH_Hotel_01_patrol",
	LHHotel02 = "Default\\Lighthouse\\LH_Hotel_02_patrol",
	LHHotel03 = "Default\\Lighthouse\\LH_Hotel_03_patrol",
	LHHotel04 = "Default\\Lighthouse\\LH_Hotel_04_patrol",

	LHFoxtrot01 = "Default\\Lighthouse\\LH_Foxtrot_01_patrol",
	LHFoxtrot02 = "Default\\Lighthouse\\LH_Foxtrot_02_patrol",
	LHFoxtrot03 = "Default\\Lighthouse\\LH_Foxtrot_03_patrol",

	LHGolf01 = "Default\\Lighthouse\\LH_Golf_01_patrol",
	LHGolf02 = "Default\\Lighthouse\\LH_Golf_02_patrol",
	LHGolf03 = "Default\\Lighthouse\\LH_Golf_03_patrol",
	LHGolf04 = "Default\\Lighthouse\\LH_Golf_04_patrol",

}